spring:
  application:
    name: distributed-job-queue
  datasource:
    url: jdbc:postgresql://localhost:5432/JobQueue
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

worker:
  batch-size: 10
  poll-delay: 5000

recovery:
  batch-size: 50
  timeout-minutes: 5
  poll-delay: 60000

job:
  max-attempts: 3